---
title: "2023년 11월 22일 3교시 요약"
tag: 202311_school
---

```java
try {
    int c = a/b; //산술오류 발생시 개발자는 어떻게 유도할 것인가?
    System.out.printf("%d / %d = %d \n", a,b,c);
} catch (ArithmeticException ae) {
    String caust = ae.getMessage();	
    System.err.println("분모에 0을 입력하면 안됩니다.");
} finally {
    System.out.println("예외발생과 무관하게 실행되는 블럭");
}

System.out.println("프로그램 종료");
```

- try_catch 구문은 예외를 처리하는 가장 기본적인 구문이다.
- try 블럭 안에 예외가 일어날지도 모르는 코드를 넣어주고 여기서 예외가 발생하면 catch 블럭이 실행된다.
- finally 블럭은 예외와 관계없이 무조건 실행되는 블럭이고 이 모든 블럭을 거쳐온 후에 마지막 출력 메소드가 실행된다. 

- **try**: 예외가 발생할 가능성이 있는 코드를 넣는 곳이다. 여러개의 예외가 발생한 때에는 아래 catch 블럭을 여러개 만들어주면 된다.
- **catch**: 예외가 발생하면 이 블럭 안의 코드를 실행한다.
  - 단, 괄호() 안의 예외에서 벗어난 예외는 발생해도 잡을 수 없다. 
  - 따라서 어떤 예외를 넣어줄지도 중요하다. 
  - 괄호 안의 예외는 하나만 사용할 수 있기 때문에 여러 개의 예외를 잡고 싶은 경우에는 이 블럭을 여러개 선언해줘야 한다.(다중 catch)
  - catch 블럭 하나만으로만 예외를 잡고 싶다면 예외 클래스의 최상위 클래스인 Exception을 넣어주면 된다.(Exception ae)
  - 다만 이럴 경우 어떤 예외가 발생하든 일률적으로 처리해야한다는 단점이 있다.
  - 각각의 오류에 맞는 대응을 하고 싶다면 instanceof 를 사용하여 대응해줘도 된다.
- **finally**: 예외 발생 여부와 상관없이 실행되는 블럭으로 데이터베이스에서 마지막 정리 작업을 할 때 주로 이용된다.

```java
System.out.print("숫자 2개 입력: ");
Scanner sc = new Scanner(System.in);

try {
    //숫자가 아닌 문자를 입력하면 오류가 발생할 수 있음
    int a = sc.nextInt();
    int b = sc.nextInt();
    
    //0을 입력하면 나눌때 오류가 발생할 수 있음
    int c = a/b;
    System.out.printf("%d / %d = %d \n", a,b,c);
} catch (Exception ae) {
    if(ae instanceof ArithmeticException) {
        String caust = ae.getMessage();	
        System.err.println("분모에 0을 입력하면 안됩니다.");
    }else if(ae instanceof InputMismatchException ime) {
        System.err.println("숫자만 입력해주세요.");
    }else {
        System.err.println("그외의 치명적 오류발생"+ae);
    }
} finally {
    //버퍼를 비워주는 작업은 반드시 실행해야하는 코드
    sc.nextLine();
    System.out.println("예외발생과 무관하게 실행되는 블럭");
}

System.out.println("프로그램 종료");
```